CREATE DATABASE IF NOT EXISTS fastcash;

CREATE TABLE fc_user (
	user_id			VARCHAR(255)	NOT NULL	PRIMARY KEY,
	credits			INT				NOT NULL 	DEFAULT 	0,
	is_lender		BOOL			NOT NULL	DEFAULT 	FALSE,
	created_at		TIMESTAMP 		NOT NULL	DEFAULT		CURRENT_TIMESTAMP()
);
